#!/usr/bin/env python
import os, sys

def main():
    args = sys.argv[1:]
    if len(args) < 2 or args[0] != '-r' or len(args) > 2:
        print "Only a very simple dispatch replacement is avaiable."
        print "There is only one supported format: `dispatch -r commandfile`"
        sys.exit(1)
    commandfile = args[1]
    os.system("srun _slurm_dispatch_helper '%s'" % commandfile)

if __name__ == "__main__":
    main()
